title: Wonhee GO, NLP Researcher
head_title: 🧭
url: "https://stellarway.github.io"
baseurl: ""

remote_theme: ankitsultana/researcher@gem
markdown: kramdown

favicon: true
favicon_location: ./asset/paw.png

tracking_id: #

footer: yes
theme_url: ""
theme_text: ""

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "About"
   link: "/"
#  - name: "Profile"
#    link: "/profile/"
#  - name: "Resume"
#    link: "resume.pdf"
 - name: "Contact"
   link: "contact"
